### ISSUE TITLE
Make this a terminal colour scheme?

### ISSUE THREAD

**Issue by liamaharon** [nightsense/carbonized#1]
Hi there! 

Forgive me if this is a silly question, I'm not very familiar with theming.
I love using this theme in Vim, and was wondering how I'd go about using it as a colour scheme for my terminal, or if you can recommend any similar colour schemes.

Thanks.

**Comment by nightsense** [comment]
@liamaharon glad you like it!

It depends on what terminal application you use. My [nightshell](https://github.com/nightsense/nightshell) repository, which includes carbonized, works for many terminals. If your terminal is on the list, give it a try and let me know if you have any issues.

If your terminal isn't on the list, let me know and I'll try to add support for it with a theme.

**Comment by liamaharon** [comment]
That's exactly what I was looking for, thanks @nightsense for your amazing work!
